feat: vue lab docs added
codedamn/teach.codedamn.com pull request #22
Opened 2024-04-02 15:31 UTC by IamAfnanSk

- added docs for vue labs as well
- docs links updated in `/docs/technologies` page

2024-04-02 15:32 UTC, IamAfnanSk commented
@mehulmpt @rishabhrao @Pranavtechie PTAL

2024-04-17 12:11 UTC, IamAfnanSk commented
@mehulmpt @rishabhrao @Pranavtechie ICYMI

2024-04-17 12:21 UTC, mehulmpt commented on docs/technologies/vue.md
> +cat > /home/damner/code/__labtests/config.js << EOF
Use `.labtests` folder (should be mentioned in https://teach.codedamn.com/docs/technologies/html-css as well. 

`__labtests` is deprecated now

2024-04-17 12:22 UTC, mehulmpt requested changes, later dismissed
One change, rest lgtm

2024-04-17 12:53 UTC, merged